spring.security.user.name=admin
spring.security.user.password=admin123



spring.application.name=e-commerce
server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL}
           
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}




spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


razorpay.key.id={REACT_APP_RAZORPAY_KEY}
razorpay.key.secret=399EtM9i3GOgmiJz4ncecNDW


