spring.security.user.name=admin
spring.security.user.password=admin123



spring.application.name=e-commerce
server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d9e7vfn7f7vs73a21ojg-a.ohio-postgres.render.com:5432/ecommerce_x3s5}
           
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ecommerce_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:6as2bX6wGufPmZsLt6YGFr4aOmEIZpV7}




spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


razorpay.key.id=rzp_test_TEdwiuvXS4duTr
razorpay.key.secret=399EtM9i3GOgmiJz4ncecNDW


